name: market
description: "Modern Market POS ve Stok Yönetim Sistemi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Tasarım ve Grafikler
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Veritabanı (Hive & Kalıcılık)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  
  # Veritabanı (Sqflite - Opsiyonel/Yedek)
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.5
  path: ^1.9.0

  # Barkod ve Kamera
  mobile_scanner: 5.2.2 

  # Yazıcı ve Çıktı
  blue_thermal_printer: ^1.2.3 
  esc_pos_utils_plus: ^2.0.3     

  # Araçlar
  intl: ^0.19.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Hive Kod Oluşturucular
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true